
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdf-docs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sdf-docs-sc
status:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdf-docs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sdf-docs-pvc
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdf-docs-deployment
  labels:
    app: nginx
    facility: scs
    space: sdf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      facility: scs
      space: sdf
